version: "3.9"
services:
  ### ===================
  ### APP SERVICE
  ### ===================
  order-service:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    container_name: order-service-container
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/app/
  order-service-worker:
    build:
      dockerfile: docker/worker/Dockerfile
      context: .
    container_name: order-service-worker-container
    volumes:
      - ./:/app/
    networks:
      - shared_network
networks:
  shared_network:
    name: shared_network
    external: true
  # filebeat:
  #   container_name: product-filebeat
  #   image: docker.elastic.co/beats/filebeat:6.5.1
  #   volumes:
  #     - ./docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - ./log/:/logs/
